apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: apisix-etcd-metrics
  namespace: apisix
  labels:
    app.kubernetes.io/name: etcd
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: etcd
  namespaceSelector:
    matchNames:
      - apisix
  podMetricsEndpoints:
    - port: client
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
