apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: apisix-metrics
  namespace: apisix
  labels:
    app.kubernetes.io/name: apisix
    release: prometheus
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: apisix
  namespaceSelector:
    matchNames:
      - apisix
  endpoints:
    - port: prometheus
      path: /apisix/prometheus/metrics
      interval: 15s
      scrapeTimeout: 10s
